//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNS.DataAccessLayer.Sqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Phones = new HashSet<Phone>();
            this.Relationships = new HashSet<Relationship>();
            this.Relationships1 = new HashSet<Relationship>();
        }
    
        public long contact_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string email_address { get; set; }
        public Nullable<long> address_id { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<Relationship> Relationships { get; set; }
        public virtual ICollection<Relationship> Relationships1 { get; set; }
    }
}
