//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNS.DataAccessLayer.Sqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationshipType
    {
        public RelationshipType()
        {
            this.Relationships = new HashSet<Relationship>();
        }
    
        public long relationshiptype_id { get; set; }
        public string relationshiptype1 { get; set; }
    
        public virtual ICollection<Relationship> Relationships { get; set; }
    }
}
